[package]
name = "loaned"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[[example]]
name = "tree_building"
test = true
